syms theta0(t) theta1(t) theta2(t) m0 m1 m2 L1 L2 I1 I2 g ...
    %Define the symbolic variables.
dtheta0 = diff(theta0,t); %Linear velocity of cart
dtheta1 = diff(theta1,t); %Angular velocity of first rod
dtheta2 = diff(theta2,t); %Angular velocity of second rod

g = 9.81;             %Gravity Constant
L1 = 0.5;             %Lenght of first rod
L2 = 0.25;            %Lenght of first rod
m0 = 1;             %Mass of cart
m1 = 0.2;            %Mass of first rod
m2 = 0.4;             %Mass of second rod
I1 = 1/12*m1*L1^2;    %Inertia of first rod
I2 = 1/12*m2*L2^2;    %Inertia of second rod

%% Calculating Equations of Motion using Lagrangian Mechanics
%Kinetic Energy
K0 = 1/2*m0*dtheta0^2;

K1 = 1/2*m1*dtheta0^2 + 1/2*(m1*L1^2+I1)*dtheta1^2 + m1*L1*dtheta0*dtheta1*cos(theta1);

K2 = 1/2*m2*dtheta0^2 + 1/2*m2*L1^2*dtheta1^2 + 1/2*(m2*L2^2+I2)*dtheta2^2 + ...
    m2*L1*dtheta0*dtheta1*cos(theta1) + m2*L2*dtheta0*dtheta2*cos(theta2) + ...
    m2*L1*L2*dtheta1*dtheta2*cos(theta1+theta2);
%Potential Energy
V1 = g*m1*L1*cos(theta1);
V2 = g*m2*(L1*cos(theta1) - L2*cos(theta2));

%Lagrangian Equation
L = simplify(expand(K0+K1+K2 - V1-V2));

%Take Lagrangian derivatives for all 3 variables
ftheta0 = simplify(expand(diff(diff(L,dtheta0),t) - diff(L,theta0)));
ftheta1 = simplify(expand(diff(diff(L,dtheta1),t) - diff(L,theta1)));
ftheta2 = simplify(expand(diff(diff(L,dtheta2),t) - diff(L,theta2)));


%% Calculate Non-Linear A matrice (Only for display purposes)
syms ddtheta0 ddtheta1 ddtheta2
%Change diff(theta0(t),t,t) variables with ddtheta0 or corresponding variables
Ftheta0 = subs(subs(subs(ftheta0,diff(theta0(t), t, t),ddtheta0),diff(theta1(t), t, t),ddtheta1),diff(theta2(t), t, t),ddtheta2);
Ftheta1 = subs(subs(subs(ftheta1,diff(theta0(t), t, t),ddtheta0),diff(theta1(t), t, t),ddtheta1),diff(theta2(t), t, t),ddtheta2);
Ftheta2 = subs(subs(subs(ftheta2,diff(theta0(t), t, t),ddtheta0),diff(theta1(t), t, t),ddtheta1),diff(theta2(t), t, t),ddtheta2);

Ftheta0 = subs(subs(subs(Ftheta0,diff(theta0(t), t),dtheta0),diff(theta1(t), t),dtheta1),diff(theta2(t), t),dtheta2);
Ftheta1 = subs(subs(subs(Ftheta1,diff(theta0(t), t),dtheta0),diff(theta1(t), t),dtheta1),diff(theta2(t), t),dtheta2);
Ftheta2 = subs(subs(subs(Ftheta2,diff(theta0(t), t),dtheta0),diff(theta1(t), t),dtheta1),diff(theta2(t), t),dtheta2);

%Get solutions of ddtheta0, ddtheta1 and ddtheta2 in terms of position and velocity
eqns = [Ftheta0, Ftheta1, Ftheta2];
vars = [ddtheta0, ddtheta1, ddtheta2];
S = solve(eqns,vars);
soltheta0 = simplify(S.ddtheta0);
soltheta1 = simplify(S.ddtheta1);
soltheta2 = simplify(S.ddtheta2);


%% Calculate Linearized System Model
% This equations taken from the master thesis (Control Theory: The Doubl Pendulum Inverted on a Cart)
% of Ian J P Crowe-Wright from University of New Mexico
% https://digitalrepository.unm.edu/cgi/viewcontent.cgi?article=1131&context=math_etds

% Seperate function as D(θ)ddθ + C(θ, dθ)dθ + G(θ) = Hu
D = [subs(Ftheta0,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{1 0 0 0 0 0}) subs(Ftheta0,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{0 1 0 0 0 0}) subs(Ftheta0,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{0 0 1 0 0 0});
     subs(Ftheta1,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{1 0 0 0 0 0}) subs(Ftheta1,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{0 1 0 0 0 0}) subs(Ftheta1,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{0 0 1 0 0 0});
     subs(Ftheta2,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{1 0 0 0 0 0}) subs(Ftheta2,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{0 1 0 0 0 0}) subs(Ftheta2,{ddtheta0 ddtheta1 ddtheta2 dtheta0 dtheta1 dtheta2},{0 0 1 0 0 0})];
 
% C becomes 0 after linearization so it is not calculated
% C = [0  -(m1+m2)*L1*sin(theta1)*dtheta1         -m2*L2*sin(theta2)*dtheta2;
%      0  0                                       m2*L1*L2*sin(theta1-theta2)*dtheta2;
%      0  -m2*L1*L2*sin(theta1-theta2)*dtheta1    0                                   ];
 
G = [subs(Ftheta0,{dtheta0 dtheta1 dtheta2 ddtheta0 ddtheta1 ddtheta2},{0 0 0 0 0 0});
     subs(Ftheta1,{dtheta0 dtheta1 dtheta2 ddtheta0 ddtheta1 ddtheta2},{0 0 0 0 0 0});
     subs(Ftheta2,{dtheta0 dtheta1 dtheta2 ddtheta0 ddtheta1 ddtheta2},{0 0 0 0 0 0})];

% Firs input is the force on the cart.
% Second input is the torque generated by servo between two rods
H = [1  L1;
     0  0;
     0  1];

LD = subs(D,{theta0, theta1,theta2},{0,0,0});
LG = subs([diff(G,theta0) diff(G,theta1) diff(G,theta2)],{theta0, theta1,theta2},{0 0 0});

%[dtheta0]  =     [theta0] 
%[dtheta1]  =     [theta1] 
%[dtheta2]  =   A*[theta2]   +  B*[u1(t)]
%[ddtheta0] =     [dtheta0]       [u2(t)]
%[ddtheta1] =     [dtheta1]
%[ddtheta2] =     [dtheta2]

%Linearized A matrice
LA = [zeros(3,3)    eye(3);
      -LD\LG   zeros(3,3)];
LA = simplify(LA);

%Linearized B matrice
LB = [zeros(3,2);
      LD\H];
LB = simplify(LB);